### ISSUE TITLE
The board isn't powered if using a USB-C to USB-C cable

### ISSUE THREAD

**Issue by MarcelKr** [snakeye/ch340g-esp32#1]
When using a USB-Type-C to USB-Type-C cable to connect the board to the host, the board isn't powered. Using USB-Type-C to USB-A cable it works.

The proper circuitry on CC1 and CC2 is missing for letting the host know to provide 5V.

The circuit could look something like this. Taken from one of my projects having a circuitry for flashing a ESP32. Works fine there.
![grafik](https://user-images.githubusercontent.com/6226629/146215521-348e9df2-1c93-42c5-b3ae-2abf9d87957a.png)

**Comment by snakeye** [comment]
Oh, thank you very much for the update! I'm not using USB-C to USB-C cables myself so I missed this point. I'll update the design shortly.

**Comment by street-grease-coder** [comment]
was it updated though?

**Comment by snakeye** [comment]
@street-grease-coder Sorry, not yet. Life has been quite busy for me the last few months.

**Comment by snakeye** [comment]
Fixed in the last commit.
